@MbtxAssessment_HostAddress = http://localhost:5241

GET {{MbtxAssessment_HostAddress}}/api/happy/
Accept: application/json

###

POST {{MbtxAssessment_HostAddress}}/clients/register?clientId=my-client-2
Accept: application/json

###

GET {{MbtxAssessment_HostAddress}}/api/readings/latest
Accept: application/json

###
